### ISSUE TITLE
Implement `Serialize` on `Deserialize` for `Result<T>`

### ISSUE THREAD

**Issue by gbj** [operutka/serde-lite#2]
You implement the traits for a wide variety of standard library types, including `Option<T>`. Any chance you could add an implementation for `Result<T, E>` where `T` and `E` both already implement them? I'm using this in a web framework to reduce Wasm bundle sizes and this would be really helpful for network requests.

**Comment by operutka** [comment]
Hi @gbj! `Serialize` and `Deserialize` implementation for `Result<T, E>` is a bit problematic. That's why it hasn't been implemented in `serde-lite` so far. Of course, we could implement it the same way as `serde` does but I'm not sure if it would solve your problem.

`Result` is an enum and as such it can be represented in multiple ways (externally tagged, internally tagged, adjacently tagged; see:  https://serde.rs/enum-representations.html). `serde` uses the default representation (i.e. externally tagged) for the `Result` type. Consider the following type:

```rust
#[derive(Serialize)]
struct A {
    result: Result<String, String>,
}
```

If you try to serialize this into JSON, you'll end up either with:
```json
{"result": {"Ok": "some success message"}}
```

or for the `Err` variant:
```json
{"result": {"Err": "some error message"}}
```

This may be OK in some cases but, in my experience, people usually need to customize how enums are serialized (either rename variants, change the representation or both). This isn't a problem for enums defined in your own crate, you can serialize them however you want. For enums defined in `std` or third-party crates, you can use a simple wrapper/helper type that will either derive `Serialize`/`Deserialize` or it can also implement it in a completely custom way.

For example, if I wanted to serialize a result from an HTTP client which, I believe, is your case (based on the linked issue), I'd do something like this:

```rust
#[derive(Serialize)]
struct Response {
    ...
}

#[derive(Serialize)]
struct ErrorRepr {
    error: String,
}

impl ErrorRepr {
    fn new<T: ToString>(err: T) -> Self {
        Self { error: err.to_string() }
    }
}

struct ResultRepr<'a, T, E> {
    inner: &'a Result<T, E>,
}

impl<'a, T, E> Serialize for ResultRepr<'a, T, E>
where
    T: Serialize,
    E: Display,
{
    fn serialize(&self) -> Result<Intermediate, serde_lite::Error> {
        match self.inner {
            Ok(ok) => ok.serialize(),
            Err(err) => ErrorRepr::new(err).serialize(),
        }
    }
}

impl<'a, T, E> From<&'a Result<T, E>> for ResultRepr<'a, T, E> {
    fn from(res: &'a Result<T, E>) -> Self {
        Self { inner: res }
    }
}

trait HttpClientResultExt {
    fn to_json(&self) -> Result<String, SerializationError>;
}

impl HttpClientResultExt for Result<Response, MyError> {
    fn to_json(&self) -> Result<String, SerializationError> {
        let intermediate = ResultRepr::from(self).serialize()?;
        
        let s = serde_json::to_string(&intermediate)?;

        Ok(s)
    }
}
```

Then, considering you'd have an instance of `Result<Response, MyError>`, you could simply serialize it like this:

```rust
let res: Result<Response, Error> = ...

let s = res.to_json().unwrap();
```

This would give you results like this:
```json
{
    "status_code": 200,
    "status_msg": "OK",
    "headers": [...],
    "body": ...
}
```

or in case of an error:
```json
{
    "error": "invalid certificate"
}
```

Of course, this all is just an example. It could be implemented more efficiently if needed and it could be implemented in a similar way for `serde` and controlled by a feature flag.

The point is that `serde-lite` does not implement `Serialize` and `Deserialize` for `Result<T, E>` because we'd have to make an assumption about the target representation. If you think that the default representation, as implemented by `serde`, is fine and should be implemented here as well, feel free to create a pull request.

**Comment by gbj** [comment]
Thanks for your really detailed response to this. It sounds to me like the best course of action is to leave things as they are, and if any of my users (or anyone else!) wants to use `serde-lite` for serialization and need to serialize a `Result`, you've given everything they'd need to do that. I'm going to close this issue, and I'll direct people to your comment if they ever need it.
